// apps/svelte/src/components/Card.svelte
<script lang="ts">
  import type { Todo } from "@core/types/types";
  export let item: Todo;
  export let backgroundColor: string;
  
  export let up = (item: Todo): void => {};
  export let toggle = (item: Todo): void => {};
  export let down = (item: Todo): void => {};
  export let remove = (item: Todo): void => {};
</script>

<div class="card" style:background-color={backgroundColor}>
  <input
    type="checkbox"
    bind:checked={item.checked}
    on:click={() => toggle(item)}
    id={item.name}
  />
  <label for={item.name}>{item.name}</label>
  <div class="navigation">
    <button on:click={() => up(item)}>👍</button>
    <button on:click={() => down(item)}>👎</button>
    <button on:click={() => remove(item)}>👋</button>
  </div>
</div>

// apps/react/src/components/Card.tsx
import { useContext } from "react";
import { AppContext } from "../store/context";
import { dispatchRemove, dispatchToggle } from "../store/store";
import { ContextType } from "../types/store";
import { Todo } from "@core/types/types";
import { getHueByPos } from "@core/hue";

type Props = {
  up: () => void;
  down: () => void;
  item: Todo;
};

export function Card({ up, down, item }: Props) {
  const { dispatch } = useContext(AppContext) as ContextType;

  function onRemove() {
    dispatch(dispatchRemove(item.pos));
  }

  return (
    <div
      className="card"
      style={{ backgroundColor: `hsl(${getHueByPos(item.pos)}, 100%, 72%)` }}
    >
      <input
        type="checkbox"
        id={item.name}
        onClick={() => dispatch(dispatchToggle(item.pos))}
        defaultChecked={item.checked}
      />
      <label htmlFor={item.name}>{item.name}</label>
      <div className="navigation">
        <button onClick={up}>👍</button>
        <button onClick={down}>👎</button>
        <button onClick={onRemove}>👋</button>
      </div>
    </div>
  );
};
