// apps/svelte/src/App.svelte
<script lang="ts">
  import type { Todo } from "@core/types/types";
  import List from "./components/List.svelte";
  import { store, add } from "./store/store";

  var backlogItems: Todo[];
  var doneItems: Todo[];
  var newItem: string = "";
  store.subscribe((state) => filterLists(state.todos));

  function filterLists(todos: Todo[]) {
    backlogItems = [];
    doneItems = [];
    for (let index = 0; index < todos.length; index++) {
      const item = todos[index];
      if (item.checked === true) {
        doneItems.push(item);
      } else {
        backlogItems.push(item);
      }
    }

    backlogItems = backlogItems;
    doneItems = doneItems;
  }

  function onSubmit(event: SubmitEvent) {
    event.preventDefault();
    if (newItem === "") {
      return;
    }
    add(newItem);
    newItem = "";
  }
</script>

<div class="app">
  <h1>
    A To Do App <br />
    <span class="subtitle">with drag and drop</span>
  </h1>

  <form on:submit={onSubmit}>
    <input
      type="text"
      bind:value={newItem}
      name="newItem"
      maxlength="120"
      placeholder="What do you want to learn?"
    />
  </form>
  <div class="row">
    <List heading="List of Frameworks" items={backlogItems} />
    <List heading="Learned" items={doneItems} />
  </div>
</div>

// react-app/src/App.tsx
import React, { useMemo, useReducer, useState } from "react";
import { List } from "./components/List";
import { reducer, initState, dispatchAdd } from "./store/store";
import { AppContext } from "./store/context";

export function App () {
  const [state, dispatch] = useReducer(reducer, initState);
  const [newItem, setNewItem] = useState("");

  const { todos } = state;
  const backlogItems = todos.filter(({ checked }) => checked === false);
  const doneItems = todos.filter(({ checked }) => checked === true);

  const contextValue = useMemo(
    () => ({
      state,
      dispatch,
    }),
    [state, dispatch]
  );

  const onSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (newItem !== "") {
      dispatch(dispatchAdd(newItem));
      setNewItem("");
    }
  };

  return (
    <AppContext.Provider value={contextValue}>
      <div className="app">
        <h1>
          A To Do App <br />
          <span className="subtitle">with drag and drop</span>
        </h1>

        <form onSubmit={onSubmit}>
          <input
            type="text"
            name="newItem"
            value={newItem}
            max-length="120"
            placeholder="What do you want to learn?"
            onChange={(event) => {
              setNewItem(event.target.value);
            }}
            
          />
        </form>
        <div className="row">
          <List heading="List of Frameworks" items={backlogItems} />
          <List heading="Learned" items={doneItems} />
        </div>
      </div>
    </AppContext.Provider>
  );
};
