// src/components/Card.jsx
import React, { useContext } from "react";
import { AppContext } from "../context";

export const Card = function ({ up, down,item }) {
  const {toggle} = useContext(AppContext);

  const startHue = 280;
  const hue = startHue - item.pos * 10;
  return (
    <div className="card" style={{backgroundColor: `hsl(${hue}, 100%, 72%)`}}>
      <input
        type="checkbox"
        id={item.name}
        onClick={() => toggle(item)}
        defaultChecked={item.checked}
      />
      <label htmlFor={item.name}>
        {item.name}
      </label>
      <div className="navigation">
        <button onClick={up}>👍</button>
        <button onClick={down}>👎</button>
      </div>
    </div>
  );
};

// apps/svelte/src/components/Card.svelte
<script lang="ts">
  import type { Todo } from "@core/types/types";
  export let item: Todo;
  export let backgroundColor: string;
  
  export let up = (item: Todo): void => {};
  export let toggle = (item: Todo): void => {};
  export let down = (item: Todo): void => {};
  export let remove = (item: Todo): void => {};
</script>

<div class="card" style:background-color={backgroundColor}>
  <input
    type="checkbox"
    bind:checked={item.checked}
    on:click={() => toggle(item)}
    id={item.name}
  />
  <label for={item.name}>{item.name}</label>
  <div class="navigation">
    <button on:click={() => up(item)}>👍</button>
    <button on:click={() => down(item)}>👎</button>
    <button on:click={() => remove(item)}>👋</button>
  </div>
</div>
