// src/components/List.jsx
import { Droppable } from "./Droppable";
import { Draggable } from "./Draggable";
import { Card } from "./Card";
import React, { useContext } from "react";
import { AppContext } from "../store/context";
import { dispatchMove, dispatchToggle } from "../store/store";
import { getHueByPos } from "../hue";

export const List = ({ heading, items }) => {
  const { dispatch } = useContext(AppContext);

  /**
   * Item dropped with in the list, change status not supported
   * @param {object} droppedItem
   * @param {number} currentPosition
   */
  const dropped = (droppedItem, currentPosition) => {
    // we dropped the item in the other list
    if(items.length === 0 || items[0].checked !== droppedItem.checked) {
      dispatch(dispatchToggle(droppedItem.pos));
    }

    dispatch(dispatchMove(droppedItem.pos, currentPosition));
  };

  /**
   * Item moved up by one
   * @param {object} item
   */
  const up = (item) => {
    const index = items.findIndex(({ pos }) => item.pos === pos);

    if (index !== 0) {
      dispatch(dispatchMove(item.pos, items[index - 1].pos));
    }
  };

  /**
   * Item moved down by one
   * @param {object} item
   */
  const down = (item) => {
    const index = items.findIndex(({ pos }) => item.pos === pos);
    if (index + 1 !== items.length) {
      dispatch(dispatchMove(item.pos, items[index + 1].pos));
    }
  };

  return (
    <div className="list">
      <h3>{heading}</h3>
      {items.map((item) => {
        return (
          <div key={item.pos}>
            <Droppable onDrop={(droppedItem) => dropped(droppedItem, item.pos)} backgroundColor={`hsl(${getHueByPos(item.pos)}, 100%, 72%)`}>
              {" "}
            </Droppable>
            <Draggable item={item}>
              <Card item={item} up={() => up(item)} down={() => down(item)} />
            </Draggable>

          </div>
        );
      })}
      <Droppable onDrop={(droppedItem) => dropped(droppedItem, items.at(-1).pos)} backgroundColor={`lightblue`}>{" "}</Droppable>
    </div>
  );
};

// apps/svelte/src/components/List.svelte
<script lang="ts">
  import type { Todo } from "@core/types/types";
  import Card from "./Card.svelte";
  import * as store from "../store/store";
  import { getHueByPos } from "@core/hue";
  import Draggable from "./Draggable.svelte";
  import Droppable from "./Droppable.svelte";
  import ListItem from "./ListItem.svelte";

  export let items: Todo[];
  export let heading: string = "default heading";
  let dragging: boolean;

  /**
   * Item moved up by one
   */
  function up(item: Todo) {
    const index = items.findIndex(({ pos }) => item.pos === pos);

    if (index !== 0) {
      store.move(item.pos, items[index - 1].pos);
    }
  }

  /**
   * Item moved down by one
   */
  function down(item: Todo) {
    const index = items.findIndex(({ pos }) => item.pos === pos);
    if (index + 1 !== items.length) {
      store.move(item.pos, items[index + 1].pos);
    }
  }

  /**
   * toggle Item
   * @param item
   */
  function toggle(item: Todo) {
    store.toggle(item.pos);
  }

  /**
   * remove item
   * @param item
   */
  function remove(item: Todo) {
    store.remove(item.pos);
  }

</script>

<div class="list">
  <h3>{heading}</h3>
  {#each items as item}
    <div>
      <ListItem {item}>
        <Card
          backgroundColor={`hsl(${getHueByPos(item.pos)}, 100%, 72%)`}
          {item}
          {up}
          {down}
          {toggle}
          {remove}
        />
      </ListItem>
    </div>
  {/each}
</div>
